# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: userservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'userservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11userservice.proto\x12\x19\x65xamples.error_handler.v1\"0\n\x0cUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"7\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\xaa\x02\n\x0bUserService\x12]\n\nCreateUser\x12&.examples.error_handler.v1.UserRequest\x1a\'.examples.error_handler.v1.UserResponse\x12]\n\nDeleteUser\x12&.examples.error_handler.v1.UserRequest\x1a\'.examples.error_handler.v1.UserResponse\x12]\n\nUpdateUser\x12&.examples.error_handler.v1.UserRequest\x1a\'.examples.error_handler.v1.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERRESPONSE']._serialized_start=48
  _globals['_USERRESPONSE']._serialized_end=96
  _globals['_USERREQUEST']._serialized_start=98
  _globals['_USERREQUEST']._serialized_end=153
  _globals['_USERSERVICE']._serialized_start=156
  _globals['_USERSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
