# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/protoc-gen-connecpy.  DO NOT EDIT!
# source: contextawareservice.proto

from typing import Iterable, Mapping, Protocol

from connecpy.client import ConnecpyClient, ConnecpyClientSync
from connecpy.code import Code
from connecpy.exceptions import ConnecpyException
from connecpy.headers import Headers
from connecpy.server import (
    ConnecpyASGIApplication,
    ConnecpyWSGIApplication,
    Endpoint,
    ServerInterceptor,
    ServiceContext,
)
import contextawareservice_pb2 as contextawareservice__pb2


class ContextAwareService(Protocol):
    async def GetContextInfo(
        self, req: contextawareservice__pb2.ContextRequest, ctx: ServiceContext
    ) -> contextawareservice__pb2.ContextResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")

    async def SimpleMethod(
        self, req: contextawareservice__pb2.ContextRequest, ctx: ServiceContext
    ) -> contextawareservice__pb2.ContextResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")


class ContextAwareServiceASGIApplication(ConnecpyASGIApplication):
    def __init__(
        self,
        service: ContextAwareService,
        *,
        interceptors: Iterable[ServerInterceptor] = (),
        max_receive_message_length=1024 * 100 * 100,
    ):
        super().__init__(
            endpoints={
                "/contextaware.v1.ContextAwareService/GetContextInfo": Endpoint[
                    contextawareservice__pb2.ContextRequest,
                    contextawareservice__pb2.ContextResponse,
                ](
                    service_name="ContextAwareService",
                    name="GetContextInfo",
                    function=getattr(service, "GetContextInfo"),
                    input=contextawareservice__pb2.ContextRequest,
                    output=contextawareservice__pb2.ContextResponse,
                    allowed_methods=("POST",),
                ),
                "/contextaware.v1.ContextAwareService/SimpleMethod": Endpoint[
                    contextawareservice__pb2.ContextRequest,
                    contextawareservice__pb2.ContextResponse,
                ](
                    service_name="ContextAwareService",
                    name="SimpleMethod",
                    function=getattr(service, "SimpleMethod"),
                    input=contextawareservice__pb2.ContextRequest,
                    output=contextawareservice__pb2.ContextResponse,
                    allowed_methods=("POST",),
                ),
            },
            interceptors=interceptors,
            max_receive_message_length=max_receive_message_length,
        )

    @property
    def path(self):
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/contextaware.v1.ContextAwareService"


class ContextAwareServiceClient(ConnecpyClient):
    async def GetContextInfo(
        self,
        request: contextawareservice__pb2.ContextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> contextawareservice__pb2.ContextResponse:
        method = "POST"
        return await self._make_request(
            url="/contextaware.v1.ContextAwareService/GetContextInfo",
            method=method,
            headers=headers,
            request=request,
            timeout_ms=timeout_ms,
            response_class=contextawareservice__pb2.ContextResponse,
        )

    async def SimpleMethod(
        self,
        request: contextawareservice__pb2.ContextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> contextawareservice__pb2.ContextResponse:
        method = "POST"
        return await self._make_request(
            url="/contextaware.v1.ContextAwareService/SimpleMethod",
            method=method,
            headers=headers,
            request=request,
            timeout_ms=timeout_ms,
            response_class=contextawareservice__pb2.ContextResponse,
        )


class ContextAwareServiceSync(Protocol):
    def GetContextInfo(
        self, req: contextawareservice__pb2.ContextRequest, ctx: ServiceContext
    ) -> contextawareservice__pb2.ContextResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")

    def SimpleMethod(
        self, req: contextawareservice__pb2.ContextRequest, ctx: ServiceContext
    ) -> contextawareservice__pb2.ContextResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")


class ContextAwareServiceWSGIApplication(ConnecpyWSGIApplication):
    def __init__(self, service: ContextAwareServiceSync):
        super().__init__(
            endpoints={
                "/contextaware.v1.ContextAwareService/GetContextInfo": Endpoint[
                    contextawareservice__pb2.ContextRequest,
                    contextawareservice__pb2.ContextResponse,
                ](
                    service_name="ContextAwareService",
                    name="GetContextInfo",
                    function=getattr(service, "GetContextInfo"),
                    input=contextawareservice__pb2.ContextRequest,
                    output=contextawareservice__pb2.ContextResponse,
                    allowed_methods=("POST",),
                ),
                "/contextaware.v1.ContextAwareService/SimpleMethod": Endpoint[
                    contextawareservice__pb2.ContextRequest,
                    contextawareservice__pb2.ContextResponse,
                ](
                    service_name="ContextAwareService",
                    name="SimpleMethod",
                    function=getattr(service, "SimpleMethod"),
                    input=contextawareservice__pb2.ContextRequest,
                    output=contextawareservice__pb2.ContextResponse,
                    allowed_methods=("POST",),
                ),
            }
        )

    @property
    def path(self):
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/contextaware.v1.ContextAwareService"


class ContextAwareServiceClientSync(ConnecpyClientSync):
    def GetContextInfo(
        self,
        request: contextawareservice__pb2.ContextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> contextawareservice__pb2.ContextResponse:
        method = "POST"
        return self._make_request(
            url="/contextaware.v1.ContextAwareService/GetContextInfo",
            method=method,
            headers=headers,
            timeout_ms=timeout_ms,
            request=request,
            response_class=contextawareservice__pb2.ContextResponse,
        )

    def SimpleMethod(
        self,
        request: contextawareservice__pb2.ContextRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> contextawareservice__pb2.ContextResponse:
        method = "POST"
        return self._make_request(
            url="/contextaware.v1.ContextAwareService/SimpleMethod",
            method=method,
            headers=headers,
            timeout_ms=timeout_ms,
            request=request,
            response_class=contextawareservice__pb2.ContextResponse,
        )
