# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contextawareservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "contextawareservice.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19\x63ontextawareservice.proto\x12\x0f\x63ontextaware.v1"6\n\x0f\x43ontextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0bhas_context\x18\x02 \x01(\x08"2\n\x0e\x43ontextRequest\x12\x11\n\toperation\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\xbd\x01\n\x13\x43ontextAwareService\x12S\n\x0eGetContextInfo\x12\x1f.contextaware.v1.ContextRequest\x1a .contextaware.v1.ContextResponse\x12Q\n\x0cSimpleMethod\x12\x1f.contextaware.v1.ContextRequest\x1a .contextaware.v1.ContextResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "contextawareservice_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONTEXTRESPONSE"]._serialized_start = 46
    _globals["_CONTEXTRESPONSE"]._serialized_end = 100
    _globals["_CONTEXTREQUEST"]._serialized_start = 102
    _globals["_CONTEXTREQUEST"]._serialized_end = 152
    _globals["_CONTEXTAWARESERVICE"]._serialized_start = 155
    _globals["_CONTEXTAWARESERVICE"]._serialized_end = 344
# @@protoc_insertion_point(module_scope)
